Adapt install script to not cluster name as mandatory parameter
Dynatrace/dynatrace-operator pull request #106
Opened 2021-03-29 07:12 UTC by DTMad

2021-03-29 07:17 UTC, lrgar requested changes

2021-03-29 07:17 UTC, lrgar commented on deploy/install.sh
> +  if [ -n "$CLUSTER_NAME" ]; then
If I'm not mistaken, `-n` means non-empty, and this example doesn't use `CLUSTER_NAME`, so perhaps it's the other way around?

2021-03-29 07:17 UTC, lrgar commented on deploy/install.sh
> +  if [ -n "$CLUSTER_NAME" ]; then
(Kind of) Same as above.

2021-03-29 07:17 UTC, lrgar commented on deploy/install.sh
> +  "activeGateGroup": "${CLUSTER_NAME}",
I presume you don't want to use this field here, and only on the else.

2021-03-29 07:17 UTC, lrgar commented on deploy/install.sh
> +    if echo "$response" | grep "${CLUSTER_NAME}" >/dev/null 2>&1; then
So no checks if connection name is used?

2021-03-29 07:17 UTC, lrgar commented on deploy/install.sh
> +  if [ -n "$CLUSTER_NAME" ]; then
Technically you can use the connection name instead here to verify.

2021-03-29 09:41 UTC, lrgar commented on deploy/install.sh
> +  CONNECTION_NAME=$CLUSTER_NAME
```suggestion
  CONNECTION_NAME="$CLUSTER_NAME"
```

2021-03-29 09:41 UTC, lrgar commented on deploy/install.sh
> +
No need to set it.
```suggestion
```

2021-03-29 10:42 UTC, lrgar approved these changes

2021-03-29 10:52 UTC, baichinger requested changes

2021-03-29 10:52 UTC, baichinger commented on deploy/install.sh
> +  if echo "$response" | grep -FEq "\"name\":\"${CONNECTION_NAME}\""; then
Causes `grep: conflicting matchers specified` for GNU grep 3.6.

2021-03-30 06:30 UTC, lrgar approved these changes

2021-03-30 07:40 UTC, baichinger approved these changes

2021-03-30 07:41 UTC, merged