Updated set-host-id-source parameter
Dynatrace/dynatrace-operator pull request #107
Opened 2021-03-29 14:33 UTC by gkrenn

Set the variable `--set-host-id-source=auto` if in infra monitoring mode

2021-03-30 06:32 UTC, lrgar requested changes

2021-03-30 06:32 UTC, lrgar commented on controllers/oneagent/daemonset.go
> +		args = append(args, "--set-host-id-source=auto")
The other way around, when feature is not InframonFeature, then you set it to `auto`. When it's in infrastructure monitoring, it must be `k8s-node-name`

2021-04-01 10:06 UTC, lrgar approved these changes

2021-04-01 11:08 UTC, DTMad approved these changes

2021-04-01 11:29 UTC, merged