Adds toleration matching node affinity to activegate
Dynatrace/dynatrace-operator pull request #1122
Opened 2022-09-05 08:03 UTC by 0sewa0

# Description
On Google Autopilot we need a Toleration that matches our node affinity for the activegate statefulset to be deployed.

Initially I only added the toleration in case of Autopilot, however this is unnecessary complication and now I just always add it. (I kept the leftover refactored code)

Also added `make deploy/gke-autopilot` that matches the capability of `make deploy/kubernetes` but its actually compatible with Autopilot.
While I was there I refactored the `make deploy/*` commands so that they no longer generate files (except the CRD 😞 )  

## How can this be tested?
- Deploy an activegate on AutoPilot
- Deploy an activegate on Kubernetes/Openshift

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/master/CONTRIBUTING.md)

2022-09-05 11:55 UTC, chrismuellner requested changes

2022-09-07 10:34 UTC, meik99 requested changes

2022-09-07 10:34 UTC, meik99 commented on src/kubeobjects/affinity.go
> +func TolerationMatchingNodeAffinity() []corev1.Toleration {
```suggestion
func TolerationForAmd() []corev1.Toleration {
```

Seems more intuative imo

2022-09-07 10:34 UTC, meik99 commented on src/kubeobjects/pod_test.go
> +	t.Run("happy path", func(t *testing.T) {
```suggestion
	t.Run("get existing pod", func(t *testing.T) {
```

2022-09-07 10:34 UTC, meik99 commented on src/kubeobjects/pod_test.go
> +	t.Run("sad path", func(t *testing.T) {
```suggestion
	t.Run("return error if pod does not exist", func(t *testing.T) {
```

2022-09-07 14:49 UTC, chrismuellner approved these changes

2022-09-07 15:10 UTC, merged