Adds step to dynamically create opencontainers labels
Dynatrace/dynatrace-operator pull request #1278
Opened 2022-10-25 14:00 UTC by meik99

Currently not a PR that is ready to review, it's a placeholder to test the ci pipeline

2022-10-27 12:08 UTC, chrismuellner requested changes

2022-10-28 08:28 UTC, meik99 commented on hack/build/ci/prepare-build-variables.sh
> +  echo "build-date=$(date --iso-8601)"
yes

2022-10-28 08:33 UTC, meik99 commented on hack/build/ci/prepare-build-variables.sh
> +  echo "build-date=$(date --iso-8601)"
output of `skopeo inspect`
```
"Labels": {
        "architecture": "x86_64",
        "build-date": "2022-09-13T17:50:09.610067",
        "changelog-url": "https://github.com/Dynatrace/dynatrace-operator/releases",
        "com.redhat.build-host": "cpt-1008.osbs.prod.upshift.rdu2.redhat.com",
        "com.redhat.component": "ubi9-micro-container",
        "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
        "description": "ActiveGate works as a proxy between Dynatrace OneAgent and Dynatrace Cluster",
        "distribution-scope": "public",
        "io.k8s.description": "Dynatrace Operator image.",
        "io.k8s.display-name": "Dynatrace Operator",
        "io.openshift.expose-services": "",
        "io.openshift.tags": "dynatrace-operator",
        "maintainer": "Dynatrace LLC",
        "name": "Dynatrace Operator",
        "org.opencontainers.image.created": "2022-10-25T15:13:43.555Z",
        "org.opencontainers.image.description": "Kubernetes / OpenShift operator to manage Dynatrace OneAgent and ActiveGate lifecycle",
        "org.opencontainers.image.licenses": "Apache-2.0",
        "org.opencontainers.image.revision": "97d6fa6e38813dffc6ee24731d6681ab2a90341b",
        "org.opencontainers.image.source": "https://github.com/Dynatrace/dynatrace-operator",
        "org.opencontainers.image.title": "dynatrace-operator",
        "org.opencontainers.image.url": "https://github.com/Dynatrace/dynatrace-operator",
        "org.opencontainers.image.version": "snapshot-ci-dynamic-labels",
        "quay.expires-after": "10d",
        "release": "1",
        "summary": "Dynatrace is an all-in-one, zero-config monitoring platform designed by and for cloud natives. It is powered by artificial intelligence that identifies performance problems and pinpoints their root causes in seconds.",
        "url": "https://www.dynatrace.com",
        "vcs-ref": "97d6fa6e38813dffc6ee24731d6681ab2a90341b",
        "vcs-type": "git",
        "vcs-url": "https://github.com/Dynatrace/dynatrace-operator.git",
        "vendor": "Dynatrace LLC",
        "version": "1.x"
    },

```
`build-date` as well as `quay.expires-after` are present

2022-10-28 08:38 UTC, meik99 commented on .github/workflows/ci.yaml
> +          images: dynatrace-operator
Added a list of image names

2022-10-28 11:26 UTC, chrismuellner requested changes

2022-10-28 11:26 UTC, chrismuellner commented on .github/workflows/ci.yaml
> +            gcr.io/dynatrace-marketplace-prod/dynatrace-operator
unused, can be removed

2022-11-02 13:15 UTC, chrismuellner approved these changes

2022-11-02 13:40 UTC, merged