E2E test for support archive log collection.
Dynatrace/dynatrace-operator pull request #1424
Opened 2022-12-16 12:53 UTC by StefanHauth

# Description
E2E tests for log collection in support archive (see #1386)

## How can this be tested?
Run E2E tests in total or selectively with
`make manifests/branch test/e2e/supportarchive`

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/master/CONTRIBUTING.md)

2022-12-21 08:25 UTC, luhi-DT commented on test/support_archive/support_archive_test.go
> +			idx := slices.IndexFunc(requiredFiles, func(file string) bool { return file == hdr.Name })
```suggestion
			index := slices.IndexFunc(requiredFiles, func(file string) bool { return file == header.Name })
```

2022-12-21 08:26 UTC, luhi-DT commented on test/support_archive/support_archive_test.go
> +			if idx != -1 {
```suggestion
			if index != -1 {
```

2022-12-21 08:27 UTC, luhi-DT commented on test/support_archive/support_archive_test.go
> +		for _, cont := range pod.Spec.Containers {
```suggestion
		for _, container := range pod.Spec.Containers {
```

2022-12-21 08:27 UTC, luhi-DT commented on test/support_archive/support_archive_test.go
> +		requiredFiles = append(requiredFiles, "operator-version.txt")
Can this be a const?

2022-12-21 08:28 UTC, luhi-DT requested changes
Comments added

2022-12-21 10:27 UTC, mjgrzybek commented on test/support_archive/support_archive_test.go
> +			idx := slices.IndexFunc(requiredFiles, func(file string) bool { return file == hdr.Name })
`idx` is fine IMHO.

2022-12-22 08:37 UTC, luhi-DT approved these changes

2022-12-22 08:39 UTC, merged