feat(helm): allow the use of a existing priorityclass
Dynatrace/dynatrace-operator pull request #1427
Opened 2022-12-21 15:30 UTC by aslafy-z

# Description

Please include the following:
- a summary of the change
- which issue is fixed (if there is one)
- relevant motivation and context

## How can this be tested?
Please include some guiding steps on how to test this change during a review.
- What environment is necessary for the change to be noticeable ?
- What needs to be enabled/applied for the change to be noticeable ?

## Checklist
- [ ] Unit tests have been updated/added
- [ ] PR is labeled accordingly
- [ ] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/master/CONTRIBUTING.md)

2022-12-21 15:57 UTC, Sissi44 approved these changes

2022-12-21 15:59 UTC, itninja-hue approved these changes

2022-12-22 09:42 UTC, chrismuellner requested changes
Thanks for the contribution!

2022-12-22 09:42 UTC, chrismuellner commented on config/helm/chart/default/templates/_csidriver.tpl
> +	{{- end -}}
```suggestion
	{{- default "dynatrace-high-priority" .Values.csidriver.existingPriorityClassName -}}
```

2022-12-22 09:42 UTC, chrismuellner commented on config/helm/chart/default/templates/Common/csi/priority-class.yaml
> +{{ if and (eq (include "dynatrace-operator.needCSI" .) "true") (not .Values.csidriver.existingPriorityClassName) }}
this could be combined in a function, e.g. `needPriorityClass`

2023-02-01 08:33 UTC, chrismuellner commented
@aslafy-z are you planning on getting this merged? If not, we can finish it up and add this functionality at a later point.

2023-02-01 09:21 UTC, aslafy-z commented
@chrismuellner I did the requested changes. Please have a new look!

2023-02-01 09:32 UTC, itninja-hue approved these changes

2023-02-02 15:27 UTC, 0sewa0 approved these changes
LGTM (the image push ci step failing is expected for forks)

2023-02-03 07:55 UTC, chrismuellner approved these changes

2023-02-03 07:56 UTC, merged