troubleshoot command checks apiToken scopes
Dynatrace/dynatrace-operator pull request #1448
Opened 2023-01-04 17:01 UTC by aorcholski

# Description

Please include the following:
- a summary of the change
- which issue is fixed (if there is one)
- relevant motivation and context

## How can this be tested?
Please include some guiding steps on how to test this change during a review.
- What environment is necessary for the change to be noticeable ?
- What needs to be enabled/applied for the change to be noticeable ?

## Checklist
- [ ] Unit tests have been updated/added
- [ ] PR is labeled accordingly
- [ ] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/master/CONTRIBUTING.md)

2023-01-10 07:50 UTC, StefanHauth requested changes

2023-01-10 07:50 UTC, StefanHauth commented on src/cmd/troubleshoot/dynakube.go
> +	logInfof("syntax of api url is valid")
```suggestion
	logInfof("syntax of API URL is valid")
```

2023-01-10 07:50 UTC, StefanHauth commented on src/cmd/troubleshoot/dynakube.go
> +	logInfof("checking if syntax of api url is valid")
```suggestion
	logInfof("checking if syntax of API URL is valid")
```

2023-01-10 07:50 UTC, StefanHauth commented on src/cmd/troubleshoot/dynakube.go
> +	logInfof("can get latest agent version")
```suggestion
	logInfof("API token is valid, can pull latest agent version")
```

2023-01-10 15:17 UTC, 0sewa0 approved these changes

2023-01-11 14:10 UTC, StefanHauth approved these changes

2023-01-11 14:14 UTC, merged