Add check for existing cluster endpoint
Dynatrace/dynatrace-operator pull request #148
Opened 2021-05-25 07:32 UTC by DTMad

In addition to the cluster name we now also check if the Kubernetes endpoint is already registered at Dynatrace and stop proactively.

2021-05-26 14:38 UTC, mmayr-at requested changes

2021-05-31 06:43 UTC, DTMad commented on deploy/install.sh
> +  if echo "$response" | grep -Fq "\"endpointUrl\":\"${K8S_ENDPOINT}"; then
Added a comment above the two awk commands to clarify the different checks

2021-05-31 07:45 UTC, baichinger commented on deploy/install.sh
> +  if echo "$response" | grep -Fq "\"endpointUrl\":\"${K8S_ENDPOINT}"; then
Can you elaborate why `\"` must not be included?

2021-05-31 09:45 UTC, baichinger approved these changes

2021-05-31 09:53 UTC, baichinger commented on deploy/install.sh
> +  if echo "$response" | grep -Fq "\"endpointUrl\":\"${K8S_ENDPOINT}"; then
`endpointUrl` returned from Dynatrace API contains a trailing slash, whereas `K8S_ENDPOINT` deduced by the script does not.

2021-05-31 10:40 UTC, mmayr-at approved these changes

2021-05-31 10:50 UTC, merged