reduntant fields removed from dynakube status
Dynatrace/dynatrace-operator pull request #1553
Opened 2023-02-16 15:26 UTC by aorcholski

# Description

Please include the following:
- a summary of the change
- which issue is fixed (if there is one)
- relevant motivation and context

## How can this be tested?
Please include some guiding steps on how to test this change during a review.
- What environment is necessary for the change to be noticeable ?
- What needs to be enabled/applied for the change to be noticeable ?

## Checklist
- [ ] Unit tests have been updated/added
- [ ] PR is labeled accordingly
- [ ] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2023-02-28 13:42 UTC, waodim commented on src/api/v1beta1/dynakube_conversion.go
> +	dst.Status.LastClusterVersionProbeTimestamp = &v1.Time{}
Would it be better to use `metav1.Now()` instead of `v1.Time{}`?

2023-02-28 19:51 UTC, chrismuellner commented on src/controllers/dynakube/dynakube_controller.go
> +func (controller *Controller) getCommunicationHosts(ctx context.Context, dynakube *dynatracev1beta1.DynaKube) ([]dtclient.CommunicationHost, error) {
this should probably be in the `connectioninfo` package

2023-03-07 14:03 UTC, 0sewa0 requested changes

2023-03-07 14:03 UTC, 0sewa0 commented on src/controllers/dynakube/connectioninfo/reconciler.go
> +func (r *Reconciler) maintainConnectionInfoObjects() error {
```suggestion
func (r *Reconciler) maintainActiveGateConnectionInfoObjects() error {
```

2023-03-07 16:52 UTC, aorcholski commented on src/controllers/dynakube/dynakube_controller.go
> +			return false
`err` was logged in getCommunicationHosts, it is refactored a little bit now

2023-03-08 06:10 UTC, 0sewa0 approved these changes

2023-03-08 06:17 UTC, merged