Adds additional check for custom fields during version status creation (#1743)
Dynatrace/dynatrace-operator pull request #1748
Opened 2023-04-28 08:21 UTC by 0sewa0

Currently the behaviour of the oneAgent daemonset changes is a bit weird, as if you change a custom image in the DynaKube, the operator has a timeout of changing the dynakube status between 1-15 mins depending on when the last request was made. 

This is now improved by not only checking if the digest changed of the manifest we pull, but also check if the image/version value in the spec itself changed.
So now if the image/version in the `dynakube` spec changes, then we overrule the timestamp and update the version status earlier.

## How can this be tested?
1. Choose a mode where you can set `version`(example: applicationMonitoring) or `image` (example: classicFullstack).
2. Set the chosen custom field to a value that works.
3. Wait for the dynakube's status to update, (and also the resources to be deployed if applicable)
    - also make sure that it does not constantly update the version status for each reconcile, do this by checking the logs
4. Change the chosen custom field to another value 
5. Make sure that the dynakube's status to updates "instantly" (within a minute) to reflect the new custom value.

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2023-04-28 08:58 UTC, luhi-DT requested changes

2023-04-28 10:52 UTC, 0sewa0 commented on src/controllers/dynakube/version/reconciler.go
> +		if oldVersion != newVersion {
that should depend on the thing we update (so the `updater`), as activegate has no problem downgrading (AFAIK).

2023-04-28 10:55 UTC, 0sewa0 commented on src/controllers/dynakube/version/reconciler.go
> +		if !strings.Contains(oldImage, newImage) {
```
the old image is the same as the new image but with the digest added to the end of it (if a tag was provide, and we could append the digest to the end)
```

`my.repo.com:my-tag@digest != my.repo.com:my-tag` == `false` yet its the same tag, so we should update early

2023-05-02 12:36 UTC, luhi-DT commented on src/controllers/dynakube/version/reconciler.go
> +		if !strings.Contains(oldImage, newImage) {
maybe `startsWith` would be safer

2023-05-02 14:18 UTC, luhi-DT approved these changes

2023-05-02 14:25 UTC, merged