Change from env var to detection mechanism
Dynatrace/dynatrace-operator pull request #1832
Opened 2023-06-02 10:45 UTC by gkrenn

# Description

Removes the dependency of the e2e tests on the platform env var.
Openshift is automatically detected by checking if SCCs group version is available in the cluster.

## How can this be tested?

Run e2e tests in openshift and kubernetes.

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2023-06-05 14:31 UTC, 0sewa0 requested changes

2023-06-05 14:31 UTC, 0sewa0 commented on src/kubeobjects/platform.go
> +const SccGVR = "security.openshift.io/v1"
😭 🤮  (I don't have a better name, `OpenshiftSecurityGVR`, but its not much better)

2023-06-05 14:31 UTC, 0sewa0 commented on src/kubeobjects/platform.go
> +type discoveryClientCreation interface {
```suggestion
type discoveryClientProvider interface {
```

2023-06-05 14:31 UTC, 0sewa0 commented on src/kubeobjects/platform.go
> +func (p *DiscoveryClientResolver) getDiscoveryClient() (discovery.DiscoveryInterface, error) {
THERE IS NOT EVEN THE LETTER `p` IN THE TYPE NAME 😂 
```suggestion
func (resolver *DiscoveryClientResolver) getDiscoveryClient() (discovery.DiscoveryInterface, error) {
```

2023-06-26 06:42 UTC, StefanHauth commented on src/kubeobjects/platform.go
> +const SccGVR = "security.openshift.io/v1"
Does this have to be public?

2023-06-26 06:42 UTC, StefanHauth commented on test/scenarios/cloudnative/proxy/proxy.go
> +	proxy.SetupProxyWithTeardown(builder, t, testDynakube)
Matter of taste: testing.T should always be the first paramter.

2023-06-29 09:07 UTC, gkrenn commented on src/kubeobjects/platform.go
> +}
Will do

2023-06-30 06:50 UTC, 0sewa0 requested changes

2023-06-30 06:50 UTC, 0sewa0 commented on src/kubeobjects/platform.go
>  package kubeobjects
there is a `kubeobjects` under `test` (for example: https://github.com/Dynatrace/dynatrace-operator/blob/03695c1d95fe519ea50492906016410452ed8926/test/helpers/kubeobjects/environment/environment.go#L14)

as these functions are only used for testing we should have it under `/test`

2023-06-30 13:19 UTC, 0sewa0 approved these changes

2023-07-03 09:05 UTC, merged