Add events to the operator
Dynatrace/dynatrace-operator pull request #188
Opened 2021-07-09 11:25 UTC by 0sewa0

2021-07-15 13:22 UTC, meik99 requested changes

2021-07-15 13:22 UTC, meik99 commented on controllers/dynakube/updates/version.go
> +	recorder.Event(dk, corev1.EventTypeNormal, UpdateImageVersionEvent, logMessage)
if the event is fired after the method exits (if possible), the instance would have to be passed to it.

2021-07-15 13:22 UTC, meik99 commented on controllers/dynakube/updates/version.go
> +	recorder.Event(dk, corev1.EventTypeNormal, UpdateOneAgentInstallerVersionEvent, logMessage)
generally speaking, firing of events should be wrapped in functions, in this case, for example,  `fireOneAgentUpdateEvent(...)`, this way the code is easier to read

2021-07-15 13:22 UTC, meik99 commented on controllers/istio/controller.go
> +	// possible events
comment isn't really needed, since the constants already have an -Event suffix

2021-07-15 13:22 UTC, meik99 commented on controllers/istio/controller.go
> +	CreateIstioConfigurationForServiceEntryEvent         = "CreateIstioConfigurationForServiceEntry"
please also double check for all events if they really have to be exported (capitalized).

2021-07-16 08:13 UTC, meik99 requested changes

2021-07-16 08:13 UTC, meik99 commented on testing_utils/events.go
> +package testing_utils
please remove `_utils` from package name

2021-07-16 08:13 UTC, meik99 commented on controllers/webhookcerts/controller.go
> +	UpdateMutatingWebhookConfigurationEvent       = "UpdateMutatingWebhookConfiguration"
these constants do not need to be exported

2021-07-16 08:13 UTC, meik99 commented on controllers/webhookcerts/controller.go
> +	// possible events
please remove unnecessary comments

2021-07-16 08:13 UTC, meik99 commented on controllers/csi/provisioner/reconciler.go
> +	InstallAgentVersionEvent       = "InstallAgentVersion"
these constants do not need to be exported

2021-07-16 09:17 UTC, meik99 submitted a review, later dismissed

2021-07-16 09:21 UTC, meik99 approved these changes

2021-07-16 11:32 UTC, meik99 approved these changes

2021-07-23 12:51 UTC, meik99 requested changes

2021-07-23 12:51 UTC, meik99 commented on webhook/server/server.go
> +	MissingDynakubeEvent = "MissingDynakube"
as far as I can see, these constants are not used anywhere but in this package. So they do not need to be exported (capitalized)

2021-07-23 12:51 UTC, meik99 commented on webhook/server/server_test.go
> +		recorder:  record.NewFakeRecorder(10),
please do not use magic numbers. move `10` to a constant

2021-07-27 09:14 UTC, DTMad approved these changes

2021-07-27 11:17 UTC, merged

2021-08-06 09:28 UTC, baichinger commented on controllers/csi/provisioner/reconciler.go
> +	installAgentVersionEvent       = "InstallAgentVersion"
The _Version_ component in the name and in the description is pretty redundant. Installing an agent is always in context of a version.

2021-08-06 09:28 UTC, baichinger commented on controllers/csi/provisioner/reconciler.go
> +			"Installed agent version: %s to envDir: %s", ver, envDir)
Message lacks the information about the node. This field must be available to be useful.