Add image import to synk to publish image workflow
Dynatrace/dynatrace-operator pull request #1885
Opened 2023-06-21 14:47 UTC by StefanHauth

# Description

Automatically import images of new releases into our Synk integration.

## How can this be tested?
You need to create a new release tag, see if the workflow run of "publish_image" was succesful and check in Snyk if the new image is listed.

## Checklist
- [n/a] Unit tests have been updated/added
- [x] PR is labeled accordingly
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2023-06-30 11:09 UTC, chrismuellner requested changes

2023-06-30 11:09 UTC, chrismuellner commented on hack/build/ci/snyk-image-import.sh
> +     --data-binary "{
can we split the payload into a separate variable and build it later so it's easier to read?

2023-06-30 11:09 UTC, chrismuellner commented on hack/build/ci/snyk-image-import.sh
> +rc=$(echo "$response" | grep HTTP/ | cut -d ' ' -f2)
is it enough to just check curl for an exit code of 0?

2023-06-30 11:09 UTC, chrismuellner commented on hack/build/ci/snyk-image-import.sh
> +response=$(curl --include \
we could also replace this with a dedicated action as suggested by @luhi-DT : https://github.com/marketplace/actions/http-request-action

2023-07-03 09:34 UTC, luhi-DT approved these changes

2023-07-03 09:58 UTC, merged