Adds metrics for csi driver
Dynatrace/dynatrace-operator pull request #189
Opened 2021-07-13 13:14 UTC by 0sewa0

2021-07-15 12:01 UTC, DTMad approved these changes

2021-07-15 12:23 UTC, meik99 requested changes

2021-07-15 12:23 UTC, meik99 commented on controllers/csi/driver/server.go
> +				break L
please use the for loop with a condition instead of breaking with a label

2021-07-15 12:23 UTC, meik99 commented on controllers/csi/driver/server.go
> +	}
should be moved into its own function

2021-07-15 12:23 UTC, meik99 commented on controllers/csi/driver/server.go
> +		version := tmp[len(tmp)-2]
`2` should be stored in a constant

2021-07-15 12:23 UTC, meik99 commented on controllers/csi/driver/server.go
> +	AgentsVersionsMetric = prometheus.NewGaugeVec(prometheus.GaugeOpts{
is there a reason this is capitalized but the other metrics are not?

2021-07-15 12:23 UTC, meik99 commented on controllers/csi/gc/binaries_test.go
> +	// ^ the in memory file system doesn't provide size so its always 0 evethough it shouldn't be
remove unused code

2021-07-16 08:03 UTC, meik99 approved these changes

2021-07-16 08:16 UTC, merged