Add namespace_mapping_controller
Dynatrace/dynatrace-operator pull request #200
Opened 2021-07-28 12:51 UTC by DTMad

In order to replicate the init.sh script as a secret into the namespaces the matchSelector of the codeModules indicate we implemented a namespace_mapping_controller which controls a ConfigMap in which we have a direct mapping between CustomResources and namespaces to monitor.

The namespace_controller now just takes care of updating this ConfigMap and adding corresponding entries to it instead of replicating the secret. This logic will be implemented and merged into this branch by @aorcholski 

Additionally a timestamp within the OneAgent status got removed.

2021-07-29 11:47 UTC, meik99 requested changes

2021-07-29 11:47 UTC, meik99 commented on controllers/namespace_mapping/namespace_mapping_controller.go
> +func (r *ReconcileNamespaceMapping) prepareScriptForDynaKube(dk string, kubeSystemUID types.UID, infraMonitoringNodes map[string]string) (*script, error) {
Nitpick: `dk` should be `dkName` since `dk` is usually used to describe the actual instance

2021-07-29 11:47 UTC, meik99 commented on controllers/namespace_mapping/namespace_mapping_controller.go
> +
Can be moved to its own function, e.g.: 'prepareProxyForScript'

2021-07-29 11:47 UTC, meik99 commented on controllers/namespace_mapping/namespace_mapping_controller.go
> +	}
Can be moved to its own function, e.g.: 'prepareTrustedCAsForScript'

2021-08-30 13:22 UTC, gkrenn commented on api/v1alpha1/dynakube_types.go
> +	Selector *metav1.LabelSelector `json:"namespaceSelector,omitempty"`
We should add this Selector to our config/samples/cr.yaml too

2021-09-15 09:12 UTC, 0sewa0 commented
closed because of https://github.com/Dynatrace/dynatrace-operator/pull/241

2021-09-15 09:12 UTC, closed without merging