Add missing usage of EdgeConnect Spec for: Env, Resources, NodeSelector, Toleration, TopologySpreadConstraints
Dynatrace/dynatrace-operator pull request #2092
Opened 2023-09-06 12:26 UTC by andriisoldatenko

## Description

This PR fixes the absence of a few missing fields from CRD that are landed correctly yo deployment:

Missing fields:
* Env
* resources
* NodeSelector
* Tolerations
* TopologySpreadConstraints

## How can this be tested?

```
kubectl apply -f - <<EOF
apiVersion: dynatrace.com/v1alpha1
kind: EdgeConnect
metadata:
  name: andrii-test
  namespace: dynatrace
spec:
  apiServer: "<tenant>.dev.apps.dynatracelabs.com"
  oauth:
    clientSecret: edge-connect-client-secret
    endpoint: https://<sso-url-here>/sso/oauth2/token
    resource: urn:dtenvironment:<tenant>
 env: 
   - name: DEBUG
     value: "true"
EOF
```

Check env vars of the pod has DEBUG=true:
```
k get pods andrii-test-5d894dbcf9-wn8p5 -o=jsonpath='{range .items[*]}{.spec.containers[*].env}' | jq
[
  {
    "name": "DEBUG",
    "value": "true"
  },
  {
    "name": "EDGE_CONNECT_NAME",
    "value": "andrii-test"
  },
  {
    "name": "EDGE_CONNECT_API_ENDPOINT_HOST",
    "value": "duc19273.dev.apps.dynatracelabs.com"
  },
  {
    "name": "EDGE_CONNECT_OAUTH__ENDPOINT",
    "value": "https://sso-dev.dynatracelabs.com/sso/oauth2/token"
  },
  {
    "name": "EDGE_CONNECT_OAUTH__RESOURCE",
    "value": "urn:dtenvironment:duc19273"
  }
]
➜  dynatrace-operator git:(improve-edgeconnect-deployment)
```

## Checklist

- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2023-09-06 14:03 UTC, 0sewa0 approved these changes

2023-09-06 14:53 UTC, 0sewa0 requested changes

2023-09-06 14:53 UTC, 0sewa0 commented on src/controllers/edgeconnect/deployment/deployment.go
> +	mandatoryEnvVars := []corev1.EnvVar{
the current way we handle user set envs is that they should take precedent, no matter what

we are going to tackle this topic later codebase wide(AND document the decision), if we want to be smarter about or not, but right now we should let the user envs take precedent

2023-09-06 15:03 UTC, luhi-DT submitted a review, later dismissed

2023-09-07 05:24 UTC, waodim approved these changes
code LGTM and tested it

2023-09-07 06:47 UTC, 0sewa0 approved these changes
tested it, overwritten a default env successfully

2023-09-07 07:34 UTC, merged