Add seccompProfile on the POD level
Dynatrace/dynatrace-operator pull request #2189
Opened 2023-10-09 12:12 UTC by aorcholski

## Description

Currently the `seccompProfile` is set on the container level only. Kyverno Policy prefers the profile to be set on the container level and the POD level.

`podSecurityContext` field has been added to `operator` and `webhook` sections of `values.yaml` file to make `seccompProfile` configurable on the POD level. 

In case of ActiveGate statefulset the `seccompProfile` field has been added on the POD level. It is hard-coded value.

Summarizing:
- `seccompProfile`s are defined on both levels (by default)
- `seccompProfile`s can be configured on both levels

## How can this be tested?
1) Use helm tests:
```
make test/helm
```

2) Modify `values.yaml` file and deploy the operator using `make deploy/kubernetes` command. Check if `seccompProfile`s are set accordingly to the `values.yaml`.

For example set the following value in the `values.yaml` file:
```
webhook:
  ...
  securityContext:
    seccompProfile:
      type: Unconfined
```
**Operator POD**:
```
kubectl -n dynatrace get -o json pod/dynatrace-operator-5586cf87f5-xzsm7 | jq -r '.spec.containers[] | .name, .securityContext.seccompProfile'

kubectl -n dynatrace get -o json pod/dynatrace-operator-5586cf87f5-xzsm7 | jq -r '.spec.securityContext.seccompProfile'
```
Output:
containers:
```
dynatrace-operator
{
  "type": "RuntimeDefault"
}
```
pod:
```
{
  "type": "RuntimeDefault"
}
```
**Webhook POD**:
```
kubectl -n dynatrace get -o json pod/dynatrace-webhook-6f769cc6fd-5gc8z | jq -r '.spec.containers[] | .name, .securityContext.seccompProfile'

kubectl -n dynatrace get -o json pod/dynatrace-webhook-6f769cc6fd-5gc8z | jq -r '.spec.securityContext.seccompProfile'
```
Output:
containers:
```
webhook
{
  "type": "Unconfined"
}
```
pod:
```
{
  "type": "RuntimeDefault"
}
```

3) Deploy simple Dynakube and check ActiveGate pod:
```
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  apiUrl: <api url>
  activeGate:
    capabilities:
      - routing
  oneAgent:
    cloudNativeFullStack: {}
```
**ActiveGate POD**:
```
 kubectl -n dynatrace get -o json pod/dynakube-activegate-0 | jq -r '.spec.containers[] | .name, .securityContext.seccompProfile'
 
 kubectl -n dynatrace get -o json pod/dynakube-activegate-0 | jq -r '.spec.securityContext.seccompProfile'
```
Output:
containers:
```
activegate
{
  "type": "RuntimeDefault"
}
```
pod:
```
{
  "type": "RuntimeDefault"
}
```

## Checklist

- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2023-10-11 10:12 UTC, StefanHauth commented
If I understand this correctly, we now set a security context on pod and on container level, but the `seccompProfile` is not set on container level unless it is configured in `values.yaml`, right?
I think to comply with the Kyverno policies, we would have to set the `seccompProfile` to `RuntimeDefault` or `LocalHost`. I'm not sure if leaving it empty is sufficient.
We can ofc define, that the operator user has to take care of that via the `values.yaml`

And for the AG pods, I fear that not having a security context on Pod level at all won't also fly with Kyverno (I'd love to be proofen wrong on this one).

2023-10-11 10:12 UTC, StefanHauth requested changes

2023-10-11 11:28 UTC, 0sewa0 reviewed
AFAIK we should set it both the container and the pod level 🤔

2023-10-11 12:40 UTC, aorcholski commented on config/helm/chart/default/values.yaml
> +      # seccompProfile:
We set `seccompProfile` on the POD level only. 
I left commented out `seccompProfile`  as a kind of description. It is the right place if one needs the container level `seccompProfile`.

2023-10-12 06:42 UTC, 0sewa0 approved these changes

2023-10-12 10:05 UTC, StefanHauth approved these changes

2023-10-12 10:06 UTC, merged