Stabilises Codemodules e2e Test
Dynatrace/dynatrace-operator pull request #2229
Opened 2023-10-16 08:57 UTC by wepudt

## Description

- adds labeling of existing namespaces
- cleans up cut-off pod

## How can this be tested?

run codemodules with proxy e2e test/

## Checklist

- ~[ ] Unit tests have been updated/added~
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2023-10-16 09:18 UTC, waodim commented on test/helpers/proxy/proxy.go
> +		builder.WithTeardown("uninstalling outbound traffice pod", func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
```suggestion
		builder.WithTeardown("uninstalling outbound traffic pod", func(ctx context.Context, t *testing.T, config *envconf.Config) context.Context {
```suggestion

2023-10-17 06:25 UTC, StefanHauth requested changes

2023-10-17 06:25 UTC, StefanHauth commented on test/helpers/proxy/proxy.go
> +	if err != nil {
```suggestion
	if k8serror.IsNotFound(err) {
	  return ctx
	}
	require.NoError(t, err)  
	  
```

2023-10-18 09:02 UTC, StefanHauth approved these changes
LGTM

2023-10-18 09:19 UTC, merged