Make install.sh run in Bourne Shell
Dynatrace/dynatrace-operator pull request #24
Opened 2020-11-05 08:21 UTC by baichinger

2020-11-05 08:30 UTC, DTMad approved these changes

2020-11-05 09:34 UTC, arthfl requested changes
Also `json=$(...)` should be quoted :-)

2020-11-05 09:34 UTC, arthfl commented on deploy/install.sh
> +  response=$(curl -sS -X POST "${API_URL}/config/v1/kubernetes/credentials" \
`$()` should be quoted :-)

2020-11-05 11:39 UTC, arthfl requested changes

2020-11-05 11:39 UTC, arthfl commented on deploy/install.sh
> +    if [ "${CLI}" == "kubectl" ]; then
`shellcheck` complains here:
```text
   if [ "${CLI}" == "kubectl" ]; then
                  ^-- SC2039: In POSIX sh, == in place of = is undefined.
```

2020-11-05 11:43 UTC, DTMad submitted a review, later dismissed

2020-11-06 06:20 UTC, DTMad approved these changes

2020-11-06 06:50 UTC, merged