Adapt csv and remove scorecard section
Dynatrace/dynatrace-operator pull request #263
Opened 2021-09-27 08:02 UTC by DTMad

2021-09-27 08:24 UTC, chrismuellner requested changes

2021-09-27 08:24 UTC, chrismuellner commented on config/olm/kubernetes/bundle-0.2.1.Dockerfile
> -LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
Should this also be removed for `0.2.2`?

2021-10-05 11:05 UTC, meik99 requested changes

2021-10-05 11:05 UTC, meik99 commented on config/olm/kubernetes/0.1.0/bundle.Dockerfile
>  LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.3.0
the latest operator sdk is 1.13.0, please double check that this value is correct

2021-10-05 11:05 UTC, meik99 commented on config/olm/kubernetes/0.1.0/bundle/metadata/annotations.yaml
>    operators.operatorframework.io.metrics.builder: operator-sdk-v1.3.0
the latest operator sdk is 1.13.0, please double check that this value is correct

2021-10-05 11:05 UTC, meik99 commented on config/olm/kubernetes/0.2.1/manifests/dynatrace-operator.v0.2.1.clusterserviceversion.yaml
>      operators.operatorframework.io/builder: operator-sdk-v1.5.0
the latest operator sdk is 1.13.0, please double check that this value is correct

2021-10-05 11:05 UTC, meik99 commented on config/olm/kubernetes/0.2.1/metadata/annotations.yaml
>    operators.operatorframework.io.metrics.builder: operator-sdk-v1.5.0
the latest operator sdk is 1.13.0, please double check that this value is correct

2021-10-05 11:05 UTC, meik99 commented on config/olm/kubernetes/bundle-0.2.1.Dockerfile
>  LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.5.0
the latest operator sdk is 1.13.0, please double check that this value is correct

2021-10-05 11:05 UTC, meik99 commented on config/olm/openshift/0.2.1/metadata/annotations.yaml
>    operators.operatorframework.io.metrics.builder: operator-sdk-v1.5.0
the latest operator sdk is 1.13.0, please double check that this value is correct

2022-01-03 11:28 UTC, chrismuellner commented
Scorecards will be removed automatically for future releases

2022-01-03 11:28 UTC, closed without merging