Remove the synthetic preview
Dynatrace/dynatrace-operator pull request #2713
Opened 2024-02-08 15:24 UTC by 0sewa0

## Description

Removes the code related to synthetic.

Also "fixes" some of the scripts that are related to docs generation, pls check those carefully: [here](https://github.com/Dynatrace/dynatrace-operator/commit/245f16d5e44da6e1c1651dba3a6f92220686655d)

## How can this be tested?

Check that there are no remaining synthetic code/references/docs in the code.

## Checklist

- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

2024-02-08 15:28 UTC, andriisoldatenko commented
@0sewa0 could you please run `make doc/api-ref`?

2024-02-09 08:57 UTC, luhi-DT requested changes

2024-02-09 08:57 UTC, luhi-DT commented on doc/api/feature-flags.md
> -    // Deprecated: AnnotationFeatureDisableActiveGateRawImage use AnnotationFeatureActiveGateRawImage instead
why was this removed

2024-02-09 08:57 UTC, luhi-DT commented on doc/api/feature-flags.md
> -    AnnotationFeatureActiveGateRawImage  = AnnotationFeaturePrefix + "activegate-raw-image"
and this

2024-02-09 08:57 UTC, luhi-DT commented on doc/api/feature-flags.md
> -    AnnotationFeatureReadOnlyOneAgent = AnnotationFeaturePrefix + "oneagent-readonly-host-fs"
and this

2024-02-09 08:57 UTC, luhi-DT commented on doc/api/feature-flags.md
> -    AnnotationFeatureWebhookReinvocationPolicy = AnnotationFeaturePrefix + "webhook-reinvocation-policy"
and this

2024-02-09 09:47 UTC, 0sewa0 commented on doc/api/feature-flags.md
> -    AnnotationFeatureActiveGateRawImage  = AnnotationFeaturePrefix + "activegate-raw-image"
its not used

2024-02-09 09:47 UTC, 0sewa0 commented on doc/api/feature-flags.md
> -    AnnotationFeatureReadOnlyOneAgent = AnnotationFeaturePrefix + "oneagent-readonly-host-fs"
its not used

2024-02-09 09:47 UTC, 0sewa0 commented on doc/api/feature-flags.md
> -    AnnotationFeatureWebhookReinvocationPolicy = AnnotationFeaturePrefix + "webhook-reinvocation-policy"
its not used

2024-02-09 10:41 UTC, albertogdd approved these changes
LGTM

2024-02-09 10:42 UTC, luhi-DT approved these changes

2024-02-09 11:18 UTC, merged