Removes the readonly functionality
Dynatrace/dynatrace-operator pull request #273
Opened 2021-09-30 13:13 UTC by 0sewa0

2021-09-30 14:05 UTC, chrismuellner requested changes

2021-09-30 14:05 UTC, chrismuellner commented on controllers/oneagent/daemonset/volumes.go
> +			volumeMounts[idx].ReadOnly = false
Is this even needed or is the default value already enough?

2021-10-04 05:49 UTC, meik99 approved these changes

2021-10-04 06:48 UTC, chrismuellner approved these changes

2021-10-04 06:51 UTC, merged