Add validation for the custom image fields in the DynaKube
Dynatrace/dynatrace-operator pull request #3265
Opened 2024-06-10 10:34 UTC by 0sewa0

## Description

Users referencing the Dynatrace Environment image registry in the `image` field of the OneAgent and ActiveGate caused problems and unexpected behaviour in the past, so we are disallowing it via the validation webhook.

As an extra, it checks if the provided image references are even valid.
(The actual check of "is it a Dynatrace Environment image registry" is not great 😬 )

## How can this be tested?

Deploy a DynaKube where the `image` field is:
a: malformed
b: is using the Dynatrace Environment image registry

2024-06-10 10:59 UTC, andriisoldatenko approved these changes

2024-06-11 08:47 UTC, chrismuellner requested changes

2024-06-11 08:47 UTC, chrismuellner commented on pkg/webhook/validation/dynakube/image.go
> +	errorUsingTenantImageAsCustom = `The 'image' field in the %s section can't be referencing an image directly from the Dynatrace Environment.`
```suggestion
	errorUsingTenantImageAsCustom = `Custom %s image must not reference the Dynatrace Environment directly.`
```

2024-06-11 08:47 UTC, chrismuellner commented on pkg/webhook/validation/dynakube/image.go
> +	errorUnparsableImageRef = `The 'image' field in the %s section can't be parsed, make sure it's a valid image reference.`
```suggestion
	errorUnparsableImageRef = `Custom %s image can't be parsed, make sure it's a valid image reference.`
```

2024-06-11 11:27 UTC, chrismuellner approved these changes

2024-06-11 12:47 UTC, andriisoldatenko approved these changes

2024-06-11 12:58 UTC, gkrenn approved these changes

2024-06-11 13:02 UTC, merged