Add LogModule configuration options for the Operator
Dynatrace/dynatrace-operator pull request #3760
Opened 2024-09-10 09:18 UTC by 0sewa0

## Description

[K8S-10533](https://dt-rnd.atlassian.net/browse/K8S-10533)

(Re)introduce the `LogModule` spec in the DynaKube.

Only adds the type and update/generate the necessary files (api-ref, deepcopy, crd)

## How can this be tested?
Check the naming/descriptions.
Run the api-ref/deepcopy/crd generation locally, if you really want to 😅

2024-09-10 12:22 UTC, chrismuellner requested changes

2024-09-10 12:22 UTC, chrismuellner commented on pkg/api/v1beta3/dynakube/dynakube_types.go
> +	LogModuleDaemonSet LogModuleDaemonSetSpec `json:"logModuleDaemonSet,omitempty"`
shouldn't it be `logModule`?

2024-09-10 13:34 UTC, waodim approved these changes
lgtm

2024-09-11 07:45 UTC, chrismuellner approved these changes

2024-09-11 08:12 UTC, merged