Reorg codebase
Dynatrace/dynatrace-operator pull request #402
Opened 2021-12-03 09:57 UTC by 0sewa0

same as https://github.com/Dynatrace/dynatrace-operator/pull/391

2021-12-03 10:02 UTC, chrismuellner requested changes

2021-12-03 10:02 UTC, chrismuellner commented on config/manifests/bases/dynatrace-operator.clusterserviceversion.yaml
> +    repository: https://github.com/Dynatrace/dynatrace-operator/src
I don't think this is correct, the repository url didn't change

2021-12-03 10:02 UTC, chrismuellner commented on deploy/install.sh
> +    "${CLI}" apply -f https://github.com/Dynatrace/dynatrace-operator/src/releases/latest/download/kubernetes.yaml
this is the incorrect location

2021-12-03 10:02 UTC, chrismuellner commented on PROJECT
> +repo: github.com/Dynatrace/dynatrace-operator/src
repo stays the same

2021-12-03 10:02 UTC, chrismuellner commented on README.md
> +For more information please have a look at [our DynaKube Custom Resource examples](https://github.com/Dynatrace/dynatrace-operator/src/tree/master/config/samples),
incorrect url

2021-12-09 12:51 UTC, chrismuellner reviewed
What about the `version` package, it should also be under `src`?

Moving everything that has `go` code under `src` would also make sense (so testing stuff as well)...

2021-12-09 12:54 UTC, 0sewa0 commented
the `version` package is something thats only purpose is to store the version of the operator, we set it during the build process, and we only read it in the go code, so I felt that its fine to be left out

2021-12-09 16:15 UTC, chrismuellner approved these changes

2021-12-09 16:17 UTC, merged