Add telemetryService field to the DynakubeSpec
Dynatrace/dynatrace-operator pull request #4236
Opened 2024-12-19 11:26 UTC by aorcholski

[JIRA](https://dt-rnd.atlassian.net/browse/DAQ-3214)

## Description
Adds `telemetryService` field to the Dynakube spec.

The default list of protocols is used if empty `telemetryService` or empty `protocols` list is provided in the dynakube spec:
```
telemetryService: {}
```
```
telemetryService:
    protocols:
```  
The default list of protocols contains:
- otlp
- zipkin
- jaeger
- statsd

## How can this be tested?
1) unittests

2) Apply dynakube
```
spec:
  telemetryService: {}
```  
ActiveGate pod is not created.

3) Apply dynakube
```
spec:
  activeGate:
    capabilities:
    - routing
  telemetryService: {}
```  
ActiveGate pod is created with PV/PVC.

`kubectl -n dynatrace describe pod/dynakube-activegate-0`
```
DT_CAPABILITIES:            MSGrouter,log_analytics_collector,generic_ingest_enabled,otlp_ingest
```

2024-12-19 12:25 UTC, andriisoldatenko commented on pkg/api/v1beta3/dynakube/telemetryservice_props.go
> +	TelemetryServiceOtlpProtocol   = "otlp"
you can use golang-like enums (similar what k8s does)
```
type Protocol string

type Protocols []Protocol

const (
        JagerProtocol  Protocol = "jager"
        ZipkinProtocol Protocol = "zipkin"
        OtlpProtocol   Protocol = "otlp"
        StatsdProtocol Protocol = "statsd"
)
```

2024-12-19 12:27 UTC, andriisoldatenko commented on pkg/api/v1beta3/dynakube/telemetryservice_props.go
> +	TelemetryServiceOtlpProtocol   = "otlp"
or https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1524-L1534

2025-01-09 11:46 UTC, andriisoldatenko commented on pkg/api/v1beta3/dynakube/telemetryservice_props.go
> +	TelemetryServiceOtlpProtocol   TelemetryServiceProtocol = "otlp"
it's hard to read, should we name it <prtocol_name><type>: eg. `OtlpTelemetryServiceProtocol `

2025-01-09 12:21 UTC, 0sewa0 requested changes

2025-01-09 12:35 UTC, andriisoldatenko commented on pkg/api/validation/dynakube/telemetryservice.go
> +	}
these all can me simplified:
```
protocols := copy(dk.TelemetryServiceProtocols()) // or tmp := append([]int(nil), dk.TelemetryServiceProtocols()...)
slices.Sort(protocols)
if len(slices.Compact(protocols))) != len(dk.TelemetryServiceProtocols()) {return error}
```
https://pkg.go.dev/slices#Compact

2025-01-09 12:41 UTC, waodim commented on pkg/api/v1beta3/dynakube/dynakube_types.go
> +	// is deployed by the operator.
```suggestion
	// are deployed by the operator.
```

2025-01-09 12:41 UTC, waodim commented on pkg/api/v1beta3/dynakube/dynakube_types.go
> +	// is deployed by the operator.
nitpick, feel free to ignore

2025-01-13 12:35 UTC, aorcholski commented on pkg/api/validation/dynakube/telemetryservice.go
> +	}
true but then we can't tell which protocols are duplicated

2025-01-13 12:46 UTC, andriisoldatenko commented on pkg/api/validation/dynakube/telemetryservice.go
> +	}
do you really need to report it back to user? or just generic message would be enough?

2025-01-13 14:52 UTC, 0sewa0 commented on pkg/api/v1beta3/dynakube/telemetryservice_props.go
> +}
so you can go `dk.TelemetryService().IsEnabled()` and `dk.TelemetryService().GetProtocols()`

2025-01-13 16:30 UTC, aorcholski commented on pkg/api/v1beta3/dynakube/telemetryservice_props.go
> +}
I thought about it but regarding dynakube spec
- activeGate is a field
- telemetryService is a pointer

```
dk.TelemetryService() -> nil -> nil.IsEnabled() <--- it is a problem
```

2025-01-14 09:25 UTC, StefanHauth commented on pkg/api/validation/dynakube/telemetryservice.go
> +	}
If in doubt always be as verbose as possible. The list of duplicated protocols has some value for the user to quickly identify the boo-boo.

2025-01-14 12:17 UTC, 0sewa0 requested changes

2025-01-14 12:17 UTC, 0sewa0 commented on pkg/api/v1beta3/dynakube/telemetryservice/props.go
> +}
This will go boom, as the `Spec` is nillable, make it the method of the `TelemetryService` struct (similar to [KSPM](https://github.com/Dynatrace/dynatrace-operator/blob/ef1cf622916eea0875725c83d18a70b4829160c5/pkg/api/v1beta3/dynakube/kspm/props.go#L7-L10))
```
func (ts *TelemetryService) IsEnabled() bool {
	return ts.Spec != nil
}
``` 

you can have `IsEnabled` defined for the `Spec` in case of the ActiveGate as that section is not nillable

2025-01-14 12:18 UTC, 0sewa0 commented on pkg/api/v1beta3/dynakube/telemetryservice_props.go
> +}
you assumed correctly, but there is a way around it :D

2025-01-15 08:42 UTC, 0sewa0 commented on pkg/api/v1beta3/dynakube/telemetryservice/props.go
> +}
FYI: so funny thing, it (the original that seems totally impossible) works (Adam tested it, I double checked)
```
func TestBoom(t *testing.T) {
	boom := TelemetryService{
		Spec: nil,
	}

	require.False(t, boom.IsEnabled())
}
```

just to not be confusing, we will still move the method to `TelemetryService`

2025-01-15 08:53 UTC, aorcholski commented on pkg/api/v1beta3/dynakube/telemetryservice/props.go
> +}
TelemetryServiceSpec.IsEnabled replaced with TelemetryService.IsEnabled

2025-01-15 09:06 UTC, 0sewa0 approved these changes

2025-01-15 11:52 UTC, merged