Recognize skipCertCheck when looking for the image hash/version
Dynatrace/dynatrace-operator pull request #46
Opened 2020-12-04 17:03 UTC by lrgar

* Recognize skipCertCheck when looking for the image hash/version. The container runtimes still need to be updated for them to be able to pull images.
* Fix the generation of the Dynatrace's Pull Secret for ActiveGate/Managed API URLs (i.e., only put the domain as the registry.)

2020-12-07 05:53 UTC, meik99 requested changes

2020-12-07 05:53 UTC, meik99 commented on controllers/dtversion/docker.go
> +		if creds, ok := dockerConfig.Auths[r]; ok {
```suggestion
		if creds, hasCreds := dockerConfig.Auths[r]; ok {
```

2020-12-07 05:53 UTC, meik99 commented on controllers/dtversion/docker.go
> +			break
Since it's only two iterations, can the `break` be removed?

2020-12-07 05:53 UTC, meik99 commented on controllers/dtversion/docker_config.go
> +func ParseDockerConfigJSON(secret *corev1.Secret) (map[string]DockerAuth, error) {
Function is not given a json string, but a secret. Also, it doesn't return a Docker config anymore, but the authentication configurations. renaming it to something akin to `ParseDockerAuthsFromSecret` might be better

2020-12-07 05:53 UTC, meik99 commented on controllers/dtversion/docker_config.go
> +	}
Why not user the already existing `DockerConfig` struct?

2020-12-17 10:15 UTC, DTMad approved these changes

2020-12-22 09:15 UTC, meik99 submitted a review, later dismissed

2020-12-22 10:29 UTC, DTMad approved these changes

2020-12-22 10:30 UTC, merged