Use different flavor in case of arm64 in the csi-provisioner
Dynatrace/dynatrace-operator pull request #501
Opened 2022-01-25 14:43 UTC by 0sewa0

based on: https://github.com/Dynatrace/dynatrace-operator/tree/feature/support-arm64-in-csi-provisioner

2022-01-26 13:42 UTC, baichinger commented on src/controllers/csi/provisioner/agent.go
> +	}
These are constants anyways and therefore suggest to use [(implicit) build constraints](https://pkg.go.dev/cmd/go#hdr-Build_constraints).

2022-01-27 14:48 UTC, chrismuellner requested changes

2022-01-27 14:48 UTC, chrismuellner commented on src/controllers/csi/provisioner/arch/arm.go
> +const Flavor = dtclient.FlavorDefault
should be the same order in both files, so it's clearer

2022-01-28 14:05 UTC, chrismuellner approved these changes

2022-01-31 09:00 UTC, merged