Changed crdApplied to a required field
Dynatrace/dynatrace-operator pull request #559
Opened 2022-02-14 14:55 UTC by waodim

2022-02-21 11:46 UTC, gkrenn requested changes
Have you tested this? - For me the install script does not seem to enforce setting the enum.

Btw. please update `upload_test.sh` - The path to the crd does no longer exists => Should be `kubectl apply -k https://github.com/Dynatrace/dynatrace-operator/config/crd` now

2022-03-24 09:52 UTC, meik99 commented on config/helm/schema.yaml
> +    description: Please make sure you have applied the latest CRD by following the instructions in the Github Repository.
```suggestion
    description: Make sure you have applied the latest CRD by following the instructions in the Github Repository.
```

2022-03-24 09:52 UTC, meik99 commented on config/helm/schema.yaml
> +    description: Please make sure you have applied the latest CRD by following the instructions in the Github Repository.
Just a nitpick from my side

2022-04-01 12:07 UTC, 0sewa0 commented
there is a conflict according to github

2022-04-04 07:38 UTC, 0sewa0 approved these changes

2022-04-04 07:38 UTC, merged