Switch to distroless base image
Dynatrace/dynatrace-operator pull request #596
Opened 2022-02-22 16:19 UTC by chrismuellner

* Explicitly set image versions for builder image and base image
* Update livenessprobe and registrar binaries

2022-02-22 16:24 UTC, luhi-DT approved these changes

2022-02-23 08:51 UTC, gkrenn approved these changes

2022-02-23 15:11 UTC, 0sewa0 requested changes
{"level":"info","ts":"2022-02-23T15:10:02.413Z","logger":"csi-driver","msg":"publishing volume","csiMode":"app","target":"/var/lib/kubelet/pods/d18175ca-0eac-4629-8ef7-2f35f4a954c3/volumes/kubernetes.io~csi/oneagent-bin/mount","fstype":"","readonly":false,"volumeID":"csi-806275e95d7941da0bb2b29c956fc2197b348e65338384ffcd12fa683c033099","attributes":{"csi.storage.k8s.io/ephemeral":"true","csi.storage.k8s.io/pod.name":"java-glibc-56978775fb-mvgzh","csi.storage.k8s.io/pod.namespace":"java-sample","csi.storage.k8s.io/pod.uid":"d18175ca-0eac-4629-8ef7-2f35f4a954c3","csi.storage.k8s.io/serviceAccount.name":"default","dynakube":"dynakube","mode":"app"},"mountflags":[]}
        /go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921","ts":"2022-02-23T15:10:01.303Z"}E0223 15:10:02.413837       1 mount_linux.go:150] Mount failed: exec: "mount": executable file not found in $PATH
Mounting command: mount
Mounting arguments: -t overlay -o lowerdir=/data/zib50933/bin/1.237.0.20220223-091210,upperdir=/data/zib50933/run/csi-806275e95d7941da0bb2b29c956fc2197b348e65338384ffcd12fa683c033099/var,workdir=/data/zib50933/run/csi-806275e95d7941da0bb2b29c956fc2197b348e65338384ffcd12fa683c033099/work overlay /data/zib50933/run/csi-806275e95d7941da0bb2b29c956fc2197b348e65338384ffcd12fa683c033099/mapped
Output: 
{"error":"rpc error: code = Internal desc = failed to mount oneagent volume: mount failed: exec: \"mount\": executable file not found in $PATH
Mounting command: mount

2022-03-04 12:02 UTC, gkrenn approved these changes
- Add glibc versions of mount/umount
- Fix livenessprobe of csi registrar

@luhi-DT @chrismuellner

2022-03-09 14:42 UTC, 0sewa0 approved these changes

2022-03-11 12:38 UTC, merged