Change CSI reconciliation to install only if package does not exist
Dynatrace/dynatrace-operator pull request #601
Opened 2022-02-28 09:26 UTC by gkrenn

Process agents that depend on the CSI driver fail monitoring if the underlying files are exchanged.

This fix will prevent installing the agent, if the files already exist on the node.

The bug was triggered by setting a different version on the tenant, but switching back to the old version again, which triggered an install on the provisioner.

2022-02-28 09:55 UTC, chrismuellner requested changes

2022-02-28 09:55 UTC, chrismuellner commented on src/controllers/csi/provisioner/agent.go
> +			"installedVersion", installedVersion,
```suggestion
			"target version", targetVersion,
			"installed version", installedVersion,
```
consistency

2022-02-28 11:52 UTC, 0sewa0 approved these changes

2022-02-28 11:52 UTC, 0sewa0 commented on src/controllers/csi/provisioner/agent_test.go
> +func updateOneagent(t *testing.T, alreadyInstalled bool) {
such abstraction, much reuse 🍪

2022-03-01 09:07 UTC, chrismuellner approved these changes

2022-03-01 09:16 UTC, merged