POC for kuttl e2e tests
Dynatrace/dynatrace-operator pull request #610
Opened 2022-03-03 08:37 UTC by 0sewa0

# Description

Some simple kuttl tests, they work (mostly).

Reasons it might fail for you:
- sometimes there is still timeout issues
- you have less/more nodes then the test want (its not nice I know)
- `KIND` needs a lot a RAM for the tests to run and the pods to not be stuck in `Pending`

## How can this be tested?
Have `kuttl` installed and run `kubectl kuttl test` in the root of the repo, and it should work.

If you want to try it with `KIND` then in the kuttl-test.yaml, set the `startKind` to `true`.

## Checklist
- [ ] Unit tests have been updated/added
- [ ] PR is labeled accordingly

2022-03-09 12:20 UTC, chrismuellner commented
Please add a readme with instructions how to use these tests and kuttl in the right folder

2022-03-30 12:09 UTC, meik99 requested changes

2022-03-30 12:09 UTC, meik99 commented on hack/e2e/install-kuttl.sh
> +export PATH=$PATH:/usr/local/bin
```suggestion
#!/bin/bash

if ! kubectl kuttl; then
  sudo curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.11.1/kubectl-kuttl_0.11.1_linux_x86_64
  sudo chmod +x /usr/local/bin/kubectl-kuttl
fi
```

2022-03-30 12:09 UTC, meik99 commented on Makefile
> +kuttl-oneagent: deploy
```suggestion
kuttl: 
    hack/e2e/install-kuttl.sh

kuttl-oneagent: kuttl deploy
```

2022-03-30 12:09 UTC, meik99 commented on hack/e2e/install-kuttl.sh
> +export PATH=$PATH:/usr/local/bin
also this file needs to be `chmod +x`-ed to add executable permissions

2022-04-01 13:19 UTC, gkrenn commented on hack/e2e/install-kuttl.sh
> +fi
Pls add support form MacOS: 

```#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  arch=`uname -m`
  ostype=darwin
else
  arch=linux
  ostype=linux
fi

version=0.11.1
installurl=https://github.com/kudobuilder/kuttl/releases/download/v${version}/kubectl-kuttl_${version}_${ostype}_${arch}

if ! kubectl kuttl; then
  echo Download from: $installurl
  sudo curl -Lo /usr/local/bin/kubectl-kuttl $installurl
  sudo chmod +x /usr/local/bin/kubectl-kuttl
fi
```

2022-04-01 13:40 UTC, gkrenn commented on src/testing/kuttl/create-dynakube-base.sh
> +
Would add check for ns: `kubectl create ns dynakube`

2022-04-01 14:10 UTC, gkrenn commented on src/testing/kuttl/create-dynakube-base.sh
> +
Ah, sorry, misunderstood, ignore this comment

2022-04-04 11:35 UTC, meik99 approved these changes

2022-04-04 12:13 UTC, merged