Refactors address_of to use Go 1.18 generics
Dynatrace/dynatrace-operator pull request #654
Opened 2022-03-18 11:15 UTC by toszr

# Description

Refactors `address_of` package to make use of the brand new Go 1.18 generics (see [official tutorial](https://go.dev/doc/tutorial/generics)).

## How can this be tested?
`make lint && make test`

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly

2022-04-28 11:39 UTC, mjgrzybek approved these changes

2022-04-28 11:48 UTC, mjgrzybek requested changes

2022-04-28 13:48 UTC, toszr commented on src/controllers/dynakube/oneagent/daemonset/daemonset.go
> +		TerminationGracePeriodSeconds: address.Of[int64](defaultTerminationGracePeriod),
Actually, no - type inference won't work for pointers:
![image](https://user-images.githubusercontent.com/16673172/165767073-6ab64258-d1fe-4986-be26-41fe24b434a2.png)

2022-04-28 14:47 UTC, mjgrzybek commented on src/controllers/dynakube/oneagent/daemonset/daemonset.go
> +		TerminationGracePeriodSeconds: address.Of[int64](defaultTerminationGracePeriod),
`defaultTerminationGracePeriod` is an `int`.
`address.Of[int64]` copies argument to `int64` parameter and return pointer to it. 
It works but cleaner solution is to change `defaultTerminationGracePeriod` type to `int64` and apply suggestion above.

2022-04-29 10:57 UTC, mjgrzybek approved these changes

2022-05-04 11:15 UTC, meik99 requested changes

2022-05-04 11:15 UTC, meik99 commented on src/kubeobjects/address/address_test.go
> +		const definitelyYes = true
```suggestion
		const constantBool = true
```

2022-05-04 11:15 UTC, meik99 commented on src/kubeobjects/address/address_test.go
> +		const twentySeven = 27
```suggestion
		const constantInt = 27
```

2022-05-04 11:15 UTC, meik99 commented on src/kubeobjects/address/address_test.go
> +		roughlyThree := int64(4)
```suggestion
		mutableInt := int64(4)
```

2022-05-04 13:28 UTC, mjgrzybek approved these changes

2022-05-13 06:55 UTC, luhi-DT approved these changes

2022-05-13 07:04 UTC, merged