Refactor component feature and version labels
Dynatrace/dynatrace-operator pull request #726
Opened 2022-04-14 11:37 UTC by chrismuellner

# Description
The components (activegate and oneagent) managed by the operator should have their version included in the labels.

Following labels were changed:
- Replaced `component.dynatrace.com/feature` with `app.kubernetes.io/component-feature` for the oneagent mode or activegate capability
- Added `app.kubernetes.io/component-version` for the oneagent or activegate version

## How can this be tested?
Deploy a dynakube with any oneagent mode and any activegate capability enabled.

Expected labels after this change:
- oneagent:
```yaml
  labels:
    app.kubernetes.io/component: oneagent
    app.kubernetes.io/component-feature: cloud_native_fullstack
    app.kubernetes.io/component-version: 1.241.0.20220413-171953
    app.kubernetes.io/created-by: dynakube
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: snapshot-feature-version-label-components
```

```yaml
  selector:
    matchLabels:
      app.kubernetes.io/component: oneagent
      app.kubernetes.io/created-by: dynakube
      app.kubernetes.io/name: dynatrace-operator
```
activegate:
```yaml
  labels:
    app.kubernetes.io/component: activegate
    app.kubernetes.io/component-feature: activegate
    app.kubernetes.io/component-version: 1.241.0.20220414-004007
    app.kubernetes.io/created-by: dynakube
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: snapshot-feature-version-label-components
```

```yaml
  selector:
    matchLabels:
      app.kubernetes.io/component: activegate
      app.kubernetes.io/created-by: dynakube
      app.kubernetes.io/name: dynatrace-operator
```

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly

2022-04-15 06:29 UTC, mjgrzybek commented on src/controllers/dynakube/oneagent/daemonset/daemonset.go
>  	labels := kubeobjects.MergeLabels(
```suggestion
	daemonSetLabels := kubeobjects.MergeLabels(
```

2022-04-15 08:05 UTC, 0sewa0 commented on src/controllers/dynakube/oneagent/oneagent_reconciler.go
> +// getPods loads pods managed by the operator
```suggestion
// getPods loads oneagent pods managed by the operator
```

or just rename the function to `getOneAgentPods` and remove the comment as it clear enough at that point (I prefer this option 😛 )

2022-04-15 08:19 UTC, 0sewa0 commented on src/kubeobjects/labels.go
> +// and component feature, if set
```suggestion
// BuildLabels produces a set of labels that
// contain the matchLabels and 
// extra labels that can change overtime
// or depending the features that are enabled.
```

Nitpick: I think the original comment is a bit too specific, if I want to see the exact labels created then I will look at the code.

The important thing that needs to be mentioned IMO is how its different from `BuildMatchLabels`, which is that it contains labels that can change.
By not being super specific, we will not have to change the comment when we add a new label.

2022-04-19 11:02 UTC, meik99 requested changes

2022-04-19 11:02 UTC, meik99 commented on src/kubeobjects/labels.go
> +// don't change when switching operator versions
```suggestion
// doesn't change when switching operator versions
```

2022-04-19 11:02 UTC, meik99 commented on src/kubeobjects/labels.go
> +// don't change when switching oneagent or activegate mode
```suggestion
// doesn't change when switching oneagent or activegate mode
```

2022-04-19 12:50 UTC, chrismuellner commented on src/agproxysecret/secret.go
>  		corev1.SecretTypeOpaque,
out of scope of this PR

2022-04-19 14:26 UTC, 0sewa0 commented on src/kubeobjects/labels.go
> +// include oneagent/activegate mode and version
```suggestion
// include values that can change overtime
```

2022-04-19 14:29 UTC, 0sewa0 commented on src/kubeobjects/labels.go
> +// don't change when switching operator versions
```suggestion
// BuildMatchLabels creates labels that
// don't include values that change overtime
```

2022-04-19 14:29 UTC, 0sewa0 commented on src/kubeobjects/labels.go
> +// don't change when switching oneagent or activegate mode
```suggestion
// BuildMatchLabels creates labels that
// don't include values that change overtime
```

2022-04-20 14:10 UTC, 0sewa0 approved these changes

2022-04-20 14:26 UTC, merged