Add feature flag for ignoring proxy within oneAgent and activeGate
Dynatrace/dynatrace-operator pull request #737
Opened 2022-04-21 12:27 UTC by luhi-DT

# Description
Currently we have the problem, when a proxy is set in the custom resource, it will get applied to all the components (operator, oneAgent and activeGate). This is so far intended, but if there is an activeGate with the purpose of routing agents traffic, then the oneAgent will also try to connect to the activeGate using the proxy, which causes problems

## How can this be tested?
Setup the operator and set a proxy in the customResource. This proxy will get applied to dtclient, oneAgents and activeGate (if defined in the same CR). If you add one or both featureFlags

- "operator.dynatrace.com/feature-activegate-ignore-proxy=true"
- "operator.dynatrace.com/feature-oneagent-ignore-proxy=true"

proxy should not be set for activeGate and/or oneAgent

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly

2022-04-21 12:38 UTC, meik99 requested changes

2022-04-21 12:38 UTC, meik99 commented on src/controllers/activegate/reconciler/statefulset/statefulset.go
> +	return !stsProperties.DynaKube.FeatureActiveGateIgnoreProxy() && stsProperties.HasProxy()
IIRC, `stsProperties` embeds the DynaKube, so the call can be simplified to 
```suggestion
	return !stsProperties.FeatureActiveGateIgnoreProxy() && stsProperties.HasProxy()
```

2022-04-21 12:38 UTC, meik99 commented on src/controllers/activegate/reconciler/statefulset/statefulset.go
> +	return !stsProperties.DynaKube.FeatureActiveGateIgnoreProxy() && stsProperties.HasProxy()
could then be further refactored into a property of DynaKube called, e.g., `ActiveGateNeedsProxy()`.
I.e.,
```
// In properties.go
func (dynakube *DynaKube) ActiveGateNeedsProxy() bool {
  return !stsProperties.FeatureActiveGateIgnoreProxy() && stsProperties.HasProxy()
}

// In statefulset.go
if stsProperties.ActiveGateNeedsProxy() {
```

2022-04-21 12:38 UTC, meik99 commented on src/controllers/dynakube/dynakube_controller.go
> +	if !dynakubeState.Instance.FeatureActiveGateIgnoreProxy() && dynakubeState.Instance.HasProxy() {
The property mentioned before can then be used here too.  See the comment for the activegate proxy flag

2022-04-21 12:38 UTC, meik99 commented on src/controllers/dynakube/oneagent/daemonset/arguments.go
> +	if !dsInfo.instance.FeatureOneAgentIgnoreProxy() && dsInfo.hasProxy() {
can also be refactored into a Dynakube property. See the comment for the activegate proxy flag

2022-04-21 12:38 UTC, meik99 commented on src/controllers/dynakube/dynakube_controller.go
>  func (controller *DynakubeController) reconcileActiveGateProxySecret(ctx context.Context, dynakubeState *status.DynakubeState) bool {
No unit test was changed when this methods logic changed. Please edit or add an unit test accordingly

2022-04-26 09:05 UTC, 0sewa0 approved these changes

2022-04-26 09:43 UTC, merged