Bump go version to 1.18.1
Dynatrace/dynatrace-operator pull request #742
Opened 2022-04-25 09:19 UTC by mjgrzybek

# Description
Follow-up of https://github.com/Dynatrace/dynatrace-operator/pull/651

go version is set to 1.18.1.
Some problems with linters may occur when using generics. It should be addressed when working with generics.

## How can this be tested?
- build image
- execute unit tests

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly

2022-04-25 18:18 UTC, chrismuellner requested changes
version is a bit inconsistent in CI and Dockerfile.

2022-04-26 05:05 UTC, mjgrzybek commented on Dockerfile
> +    apk add --no-cache gcc musl-dev btrfs-progs-dev lvm2-dev device-mapper-static git && \
`go get` requires `git` if any of the packages is fetched from a git repository

2022-04-26 09:44 UTC, mjgrzybek commented
> version is a bit inconsistent in CI and Dockerfile.

It never was and will never be.
Container image (`golang:1.18-alpine`) and `actions/setup-go@v2` are independent and versioning granularity may differ. I'd suggest to stick just to "^1.18". 
Even if versions slightly differ in _patch_ number, it shouldn't be an issue.

2022-04-26 10:10 UTC, mjgrzybek commented on .github/workflows/ci.yml
> +          go-version: "^1.18.1"
golangci-lint [newest version](https://github.com/golangci/golangci-lint/releases) is already used.

2022-04-26 10:35 UTC, chrismuellner commented on .github/workflows/ci.yml
> +          go-version: "^1.18.1"
lint action we use exists in v3: https://github.com/golangci/golangci-lint-action/releases

2022-04-26 10:51 UTC, mjgrzybek commented on .github/workflows/ci.yml
> +          go-version: "^1.18.1"
It's only github action version - not `golangci-lint`.
We could update github actions (also `actions/setup-go@v2` -> `actions/setup-go@v3`, maybe more?) but I think it's out of scope of this PR.

2022-04-26 10:59 UTC, chrismuellner approved these changes

2022-04-26 10:59 UTC, merged