Improves makefile and makefile structure
Dynatrace/dynatrace-operator pull request #799
Opened 2022-05-24 12:29 UTC by meik99

# Description

Improves the Makefile by implementing [best practices](https://docs.cloudposse.com/reference/best-practices/make-best-practices/#use-standard-target-names-in-root-makefile).
Makes the main Makefile more readable and refactors complicated targets into their own files and folders.
This was done to improve readability, usability and maintainability of the Makefile and build system.

## How can this be tested?
Checkout the branch an run your favourite make commands.
Important ones such as `make bundle` and `make manifests` should work as before.
If there was recently work done on any target, it should still run as intended.

## Checklist
~~- [ ] Unit tests have been updated/added~~
Unit tests are not relevant for this PR as it only effects the build system
- [x] PR is labeled accordingly

2022-05-25 14:51 UTC, chrismuellner requested changes
CRD generation needs to also be updated after #793

2022-05-27 09:07 UTC, meik99 commented on hack/make/tests/helm.mk
> +test/helm/unit:
would be a bit redundant since it already has the `test/` prefix, wouldn't it?

2022-05-27 09:37 UTC, meik99 commented on Makefile
> +# What exactly it does line by line is a mystery, but the printed help text looks nice
Added breakdown of code

2022-05-27 09:38 UTC, meik99 commented on hack/make/prerequisites.mk
> +	$(info WARNING "Make sure that golangci-lint is installed, for more info see https://golangci-lint.run/usage/install/")
Replaced by `go install`-ing golangci-lint instead, as that command checks if it already exists or not

2022-05-27 09:58 UTC, meik99 commented
marking as a draft since https://github.com/Dynatrace/dynatrace-operator/pull/793 has yet to be merged completely

2022-05-30 09:18 UTC, chrismuellner commented on config/deploy/kubernetes/kustomization.yaml
> +images:
incorrectly checked in

2022-05-30 09:20 UTC, chrismuellner commented on hack/make/images.mk
> +BRANCH_IMAGE ?= quay.io/dynatrace/dynatrace-operator:snapshot-$(shell git branch --show-current | sed "s/[^a-zA-Z0-9_-]/-/g")
could `$(shell git branch --show-current | sed "s/[^a-zA-Z0-9_-]/-/g")` be moved to a variable (not named `TAG`) and reused?

2022-05-30 09:20 UTC, chrismuellner commented on hack/make/manifests/config.mk
> +CRD_OPTIONS ?= "crd:preserveUnknownFields=false, crdVersions=v1"
```suggestion
CRD_OPTIONS ?= "crdVersions=v1"
```

2022-05-30 09:27 UTC, chrismuellner commented on hack/make/manifests/openshift.mk
> +		--set autoCreateSecret=false \
same here

2022-05-30 09:28 UTC, chrismuellner commented on hack/make/prerequisites.mk
> +	go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.3.0 ;\
```suggestion
	go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0 ;\
```

2022-05-30 09:42 UTC, chrismuellner approved these changes

2022-05-30 09:49 UTC, merged