Helm development version is set to appropriate version.
Dynatrace/dynatrace-operator pull request #819
Opened 2022-06-06 15:26 UTC by aorcholski

Set helm development version to:
- 0.0.0 if master is the current branch
- < ver > if release-< ver > is the current branch
- otherwise Chart.yaml version/appVersion fields are not changed

## How can this be tested?
Execute `make bundle` command on the following branches:
- master
- release-9.99.999
- feature/set-helm-version
version/appVersion should be updated according to the requirements.

## Checklist
~~- [ ] Unit tests have been updated/added~~
- [x] PR is labeled accordingly

2022-06-08 08:06 UTC, 0sewa0 requested changes

2022-06-08 08:06 UTC, 0sewa0 commented on hack/make/manifests/crd.mk
> +	sed -i "s/^appVersion: .*/appVersion: $(CHART_VERSION)/" $(HELM_CHART_DEFAULT_DIR)/Chart.yaml
`sed -i` doesn't work on Mac os 😬

2022-06-08 09:29 UTC, 0sewa0 commented
tested it and got the following
on master:              `0.0.0` 👍 
on release-0.7:       `0.7` ❓ 
on feature branch:  nothing happened 👍 

shouldn't it be `0.7.0`  on release-0.7 ?

also something we should tackle after this PR: if we have a 0.7.1 release we will not have a separate branch for that, but the Chart.yaml should be updated to `0.7.1`, how should we go about that ?
@chrismuellner

2022-06-08 12:22 UTC, meik99 requested changes

2022-06-08 12:22 UTC, meik99 commented on hack/make/manifests/crd.mk
> +manifests/version:
That target changes helm charts, it doesn't directly influence the manifests and should therefore have a different target

2022-06-09 07:47 UTC, meik99 submitted a review, later dismissed

2022-06-09 07:47 UTC, meik99 commented on hack/make/manifests/crd.mk
> +helm/version:
```suggestion
## Sets the Helm Charts version and appVersion
helm/version:
```

2022-06-09 07:47 UTC, meik99 commented on hack/make/manifests/crd.mk
> +helm/version:
Also I meant putting this target in a different file or folder since it has nothing to do with the manifests, not just renaming it

2022-06-13 13:58 UTC, 0sewa0 approved these changes

2022-06-14 07:23 UTC, merged