Makes standalone init smarter about the envs
Dynatrace/dynatrace-operator pull request #920
Opened 2022-07-01 07:24 UTC by 0sewa0

# Description

The standalone init wants to read/setup envvars that are not necessary for data-ingest only injection, which the webhook will not provide ==> standalone init fails the pod

Now it only sets env fields to be required according to what injection is needed.

## How can this be tested?
Inject into a:
- pod that has data-ingest disabled
- pod that has oneagent disabled
- pod that has both disabled
all of these should work as expected

## Checklist
- ~[ ] Unit tests have been updated/added~
- [x] PR is labeled accordingly
- [x] I have read and understood the [contribution guidelines](/CONTRIBUTING.md)

2022-07-04 15:17 UTC, chrismuellner requested changes

2022-07-04 15:17 UTC, chrismuellner commented on src/standalone/env.go
>  func (env *environment) setOptionalFields() {
should be split into separate functions, e.g. injection/base and optional fields

2022-07-04 15:17 UTC, chrismuellner commented on src/standalone/env.go
> +	oneAgentInjected, _ := checkEnvVar(OneAgentInjectedEnv)
inconsistent check for error, could also check it for optional fields

2022-07-05 12:17 UTC, meik99 approved these changes

2022-07-05 12:47 UTC, chrismuellner approved these changes

2022-07-05 12:52 UTC, merged